### ISSUE TITLE
"Add to project dictionary" override previous dictionary

### ISSUE THREAD

**Issue by Luthaf** [yitzchak/linter-spell-project#1]
First of all, thank you very much for this project, I discovered it a week ago and it is really helpful tool in my workflow, for writing documentation or scientific articles as a non native english speaker. So thank you!

I have an issue with this project, I know this is a beta version but I wanted to report it.

If I have already some words in the `language.json` file, and then I try to add a new one using the intention "add to project dictionary", then `language.json` get overwritten and only contains the new word.

I am using `linter-spell@0.12.0` and `linter-spell-project@0.1.0` with the following atom and OS version:

```
$ atom --version
Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
$ uname -srv
Linux 3.10.0-327.36.2.el7.x86_64 #1 SMP Mon Oct 10 23:08:37 UTC 2016
$ cat /etc/redhat-release 
CentOS Linux release 7.2.1511 (Core) 
```

**Comment by yitzchak** [comment]
Did you create `language.json` after Atom was open?

**Comment by Luthaf** [comment]
No, it happen with a pre-existing language.json too.

**Comment by Luthaf** [comment]
By replacing [`addWatcher`](https://github.com/yitzchak/linter-spell-project/blob/9c79ca86c1d94ee019e3323c4036eb4e87d87f32/lib/project-dictionary.js#L28) with the following code, there is no more overwriting of the file.

```js
addWatcher () {
    this.watcher = fs.watch(this.languagePath, (type, _) => {
        if (type == 'change') {
            this.data = JSON.parse(fs.readFileSync(this.languagePath))
        }
    })
  }
```

However I get a random exception about file length in atom, that seems to come from a race condition in file reading/writing.

**Comment by yitzchak** [comment]
Thanks @Luthaf! I'll get it merged soon.

**Comment by Luthaf** [comment]
Just to make it clear, this patch does not fix every error: I still get exceptions in atom with it.

---

I think the issue here is that every call to `addWord` will write to the file, which in turn will call the watcher function, previously erasing any word in the dictionary.

**Comment by yitzchak** [comment]
Just did a patch release. Try it out.

**Comment by Luthaf** [comment]
I still get overrides of the `language.json` file with the latest release.

**Comment by yitzchak** [comment]
Try now please.

**Comment by Luthaf** [comment]
The 0.1.3 release seems to fix this! Thanks.

**Comment by yitzchak** [comment]
Awesome! Thanks for reporting!
